<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'news.features.inc';
/**
 * Title and image are link to the node or to the field_news_url_target field
 * Working directly on the "title" field was not possible because of the automatic
 * format which is not html (tag are not interpreted). So I decided to work on the 
 * "news_url_target" field
 */
function news_views_pre_render(&$view) {
	//dpm($view);
        if ($view->name == 'evenements' && $view->current_display == 'page') {
            foreach ($view->result as &$value) {
                if (!empty($value->field_field_news_url_target)) {
                    $target = (empty($value->field_field_new_window) || !$value->field_field_new_window[0]['rendered']['#markup'])? '' : ' target="_blank" ';
                    
                    $value->field_field_scald_image[0]['rendered']['#markup'] = '<a '.$target.' href="'.$value->field_field_news_url_target[0]['rendered']['#markup'].'">'.$value->field_field_scald_image[0]['rendered']['#markup'].'</a>';
                    
                    $value->field_field_news_url_target[0]['rendered']['#markup'] = 
                            '<h3 class="title-event-list"><a '.$target.' href="'.$value->field_field_news_url_target[0]['rendered']['#markup'].'">'.$value->node_title.'</a></h3>';
                }else {
                    $href = ' href="'.drupal_get_path_alias("node/".$value->nid).'" ';
                    $value->field_field_news_url_target[0]['rendered']['#markup'] = '<h3 class="title-event-list"><a href="/node/'.$value->nid.'">'.$value->node_title.'</a></h3>';
                    $value->field_field_scald_image[0]['rendered']['#markup'] = '<a '.$href.'>'.$value->field_field_scald_image[0]['rendered']['#markup'].'</a>';
                }
            }
		
	}
}
