<?php
/**
 * @file
 * Code for the Domaine d'O Page complexe feature.
 */

include_once 'domaine_d_o_page_complexe.features.inc';

/**
 * Implements hook_init().
 */
function domaine_d_o_page_complexe_init() {
  drupal_add_js(drupal_get_path('module', 'domaine_d_o_page_complexe') .'/js/domainedo_page_complex.js');
}

/**
 * Implements hook_node_view().
 */
function domaine_d_o_page_complexe_node_view($node, $view_mode, $langcode) {
  if($view_mode == "full" && $node->type=="page_complexe") {
    drupal_add_js(drupal_get_path('theme','ddobs') . '/js/jquery.matchHeight-min.js');
    drupal_add_js(drupal_get_path('theme','ddobs') . '/js/matchHeightPublicText.js');
  }
}
