<?php
/**
 * Implements hook_install().
 *
 * Performs actions to set up the site for this profile.
 *
 * @see system_install()
 */
function domainedo_config_install() {
	// Themes settings.
	theme_disable(array('bartik','seven'));
	theme_enable(array('domainedo'));
	
	// Modules settings.
	module_disable(array('toolbar'));
}

/**
 * Enable mm menu to manage mobile menu
 */
function domainedo_config_update_7001() {
  module_enable(array('mmenu'));
}